services:
    dev:
        build:
            context: ../
            dockerfile: env/Dockerfile
        environment:
            - SSH_AUTH_SOCK=/ssh-agent
        volumes:
            - ../:/app
            - ${SSH_AUTH_SOCK}:/ssh-agent
        privileged: true # Required to run podman inside container
        cgroup: host # Required for cgroup v2 delegation to nested containers
